site_name: CASVA50 Team Documentation

nav:
    - Home: index.md
    - 'Line detection': line_detection.md
    - 'Traffic sign': traffic_signs.md
    - 'How to write documentation' : howtowritedoc.md

theme:
  name: material